version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: axebench_server_1
      APP_PORT: 5000

  server:
    image: ghcr.io/willitmod/axebench-release:v3.0.1-alpha@sha256:3c0f2ffee49dbada14d313ef4fda12876b1f4fa85ef1b11283aad2692a52b979
    restart: on-failure
    stop_grace_period: 30s
    init: true
    environment:
      AXE_HOST: 0.0.0.0
      AXE_PORT: 5000
      HOME: /data
    volumes:
      - ${APP_DATA_DIR}/data:/data
